### ISSUE TITLE
[QUESTION] xtd.forms - Should anchor(), dock(), and control_layout_style() all give very different results?

### ISSUE THREAD

**Issue by jimorc** [gammasoft71/xtd#197]
# Your question

I have been attempting to place a number of controls (labels, combo_boxes, other layout controls) inside vertical_layout_panels. I have tried using anchor, dock, and content_layout_style methods, and although I think I am using them correctly, I get very different results from each and rarely if ever what I want.

The examples provided with xtd show little or no use of these methods, and little or no use of layout_panels.

Are these methods complete? Do you want questions, bug reports, etc. with sample code? Before I spend considerable time on creating sample code, I want to make sure that I am not wasting both your time and mine at present.

**Comment by gammasoft71** [comment]
# Containers development status

| container               | Finished and fonctional |
|-------------------------|-------------------------|
| collapsible_panel       | ❌ (dev started)        |
| fixed_layout_panel      | ✔️                      |
| flow_layout_panel       | ❌ (dev started)        |
| grid_layout_panel       | ❌                      |
| group_box               | ✔️                      |
| horizontal_layout_panel | ✔️                      |
| panel                   | ✔️                      |
| popup_panel             | ✔️                      |
| split_container         | ❌  (dev started)       |
| splitter_panel          | ✔️                      |
| tab_control             | ✔️                      |
| tab_page                | ✔️                      |
| table_layout_panel      | ❌ (dev started)        |
| vertical_layout_panel   | ✔️                      |


# Explanations

Perhaps some explanation is needed.

## anchor and dock

* First of all, xtd is designed (just like .Net Winforms) to work mainly with anchor or dock.
* For more information on anchor and dock see the [Position and layout of controls](https://github.com/gammasoft71/xtd/blob/master/docs/position_and_layout_of_controls.md) guide.

### Remarks

Lanchors and dock cannot be assigned to the same control. It is one or the other but not both. If you use both methods on the same control it is always the last one assigned that takes over.

Read the the [anchor](https://codedocs.xyz/gammasoft71/xtd/classxtd_1_1forms_1_1control.html#aaf1b4489cf4ad56cfcba4e619c95f56c)'s remark.

## Standard containers

### Containers
* fixed_panel
* group_box
* panel
* popup_panel
* splitter_panel
* tab_page

These containers use position, size, anchor and dock for children controls.

### Remarks

fixed_panel and panel are the same.

## Layout containers

### Containers
* flow_layout_manel
* grid_laout_panel
* horizontal_layout_panel
* vertical_layout_panel
* table_layout_panel

Layout containers have been added for developers who are used to using them in other frameworks like Qt or wxWidgets.

The role of the layout container is to manage the layout of child controls.

Layout panels can use the dock or anchor to position themselves in the parent control (Generally we use dock(dock_style::fill)). 

On the other hand, child controls of layout panel cannot use the dock or anchor properties because it is the layout panel that decides how to display them according to the chosen options.

### Horizontal layout panel styles

### Horizontal and vertical layout panel styles

#### styles

You must specify for each chid control the layout style to the layout container by the method vertical_layout_control_style for vertical_layout_style and horontal_layout_style for horizontal_layout_style.

#### width or height

You can specify the prefered width for horizontal_layout_panel or height for vertical_lyout__panel in pixel or percent depending the size_type.

#### Exapend 

A flag indicating if control is expanded to its containing layout container verticaly or horizontaly depend if vertical_layout_panel or horizontal_layout_panel.

#### size_type
* auto_size : The control should be automatically sized to share space with its peers.
* absolute : The control should be sized to an exact number of pixels. (Style by default)
* percent : The control should be sized as a percentage of the parent container.

#### content_alignment
* top_left : Content is vertically aligned at the top, and horizontally aligned on the left.
* top_center : Content is vertically aligned at the top, and horizontally aligned at the center.
* top_right : Content is vertically aligned at the top, and horizontally aligned on the right.
* middle_left : Content is vertically aligned in the middle, and horizontally aligned on the left.
* middle_center : Content is vertically aligned at the middle, and horizontally aligned at the center.
* middle_right : Content is vertically aligned at the middle, and horizontally aligned on the right.
* bottom_left : Content is vertically aligned in the bottom, and horizontally aligned on the left.
* bottom_center : Content is vertically aligned at the bottom, and horizontally aligned at the center.
* bottom_right : Content is vertically aligned at the bottom, and horizontally aligned on the right.

## Spcific containers

### Containers
* collapsible_panel : Used to group collections of controls in a collapsible panel.
* split_container : Represents a control consisting of a movable bar that divides a container's display area into two resizable panels.
* tab_control : Manages a related set of tab pages.

# Examples

## horizontal_layout_panel

* [horizontal_layout_panel](https://github.com/gammasoft71/xtd/tree/master/examples/xtd.forms.examples/containers/horizontal_layout_panel)
* [list_box](https://github.com/gammasoft71/xtd/tree/master/examples/xtd.forms.examples/controls/list_box)
* [change_parent](https://github.com/gammasoft71/xtd/tree/master/examples/xtd.forms.examples/others/change_parent)
* [group_box_and_radio_button](https://github.com/gammasoft71/xtd/tree/master/examples/xtd.forms.examples/others/group_box_and_radio_button)
* [system_sound](https://github.com/gammasoft71/xtd/tree/master/examples/xtd.forms.examples/others/system_sound)

## vertical_layout_panel

* [vertical_layout_panel](https://github.com/gammasoft71/xtd/tree/master/examples/xtd.forms.examples/containers/vertical_layout_panel)
* [process_form](https://github.com/gammasoft71/xtd/tree/master/examples/xtd.forms.examples/components/process_form)
* [form_show](https://github.com/gammasoft71/xtd/tree/master/examples/xtd.forms.examples/others/form_show)
* [group_box_and_radio_button](https://github.com/gammasoft71/xtd/tree/master/examples/xtd.forms.examples/others/group_box_and_radio_button)

# Remarks

 Soon I will write a guide with explanation and examples.

**Comment by jimorc** [comment]
Thanks. That has actually answered a number of my questions. It has given me a number of things to try.

I will review the guide when you get it written.
