### ISSUE TITLE
[QUESTION] GUI for android

### ISSUE THREAD

**Issue by Master811129** [gammasoft71/xtd#208]
Hello, thank you for your amazing project. Keep up the great work.
Is there any plan for adding the gui support for android?

**Comment by gammasoft71** [comment]
Hello,

thank you for your message.

Unfortunately no, I don't plan any GUI for Android and iOS for the moment.
The current development plan is already very full for the next few years.

I don't hide you that the idea has already crossed my mind several times that when xtd::forms would be in maintenance mode, 
I could create a new library (xtd::...) that would allow to have a portable GUI on all platforms including mobile (Android, iOS, ...).
The idea would be to have an improved xml driven GUI (like QML or XAML). But unfortunately it will not be for a long time.

Kind regards
Gammasoft

**Comment by Master811129** [comment]
OK, thank you for the detailed answer. Its totally undrstandable that making a gui library for all platforms is hard. But adding at least Android, with its huge marketshare, to xtd::forms would be a great idea. This will make the project really destinguishable among other projects and after that, maintance mode... 
However I know that you make the best decision for your project.

**Comment by gammasoft71** [comment]
Hello again,

First of all, thank you for your interest in xtd and also for proposing ideas. 

You are absolutely right to have compatibility for Android which has a large market share would set xtd apart from other projects.

But unfortunately not in the xtd::forms library which is desktop oriented with especially pixel based positioning and resizing notions. 

That's why we need an xtd::... library (no name yet), which would not be pixel and desktop oriented at all. It should be much more generic. This library will be based on xtd::forms for the destop and on the Android API through the JNI for Android and on the UIKit API for iOS, iPadOS, ...

Nothing is defined yet but the main lines are there ;-)

If you still have questions or ideas, do not hesitate to contact us.

Sincerely,
Gammasoft
