### ISSUE TITLE
[ENHANCEMENT] Use more smart pointers

### ISSUE THREAD

**Issue by elfring** [gammasoft71/xtd#216]
:thinking: How do you think about to [wrap any more pointers](https://github.com/gammasoft71/xtd/blob/80d3ab8395b64406731a545aed4ff0b198550818/src/xtd.drawing.native.wxwidgets/include/xtd/drawing/native/hdc_wrapper.h#L21 "Update candidate: class “hdc_wrapper”") with the class template “[std::unique_ptr](https://en.wikipedia.org/wiki/Smart_pointer#unique_ptr "Description for the usage of smart pointers")”?

:thought_balloon: Would you like to take [the C++ guideline “R.11: Avoid calling new and delete explicitly”](https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#r11-avoid-calling-new-and-delete-explicitly "Recommendations around allocation and deallocation") better into account?

**Comment by elfring** [comment]
Thanks for [your source code improvements](https://github.com/gammasoft71/xtd/commit/6968d09811e7b29dd86f87b9d0a76ddca1ab2b7d "Replace standard pointer by std::unique_ptr").

Were further update candidates left over? :thinking:
* https://github.com/gammasoft71/xtd/blob/022e5450ba157378f4a26f04de1b4ecb03531200/src/xtd.core/include/xtd/web/css/css_writer.h#L25
* https://github.com/gammasoft71/xtd/blob/26e93bb8e656974e347ea84abba4917b0eb8444e/src/xtd.core/src/xtd/net/sockets/send_packets_element.cpp#L32
* https://github.com/gammasoft71/xtd/blob/032935f7d6e35d8dedf26490f96e50c3b31d5045/src/xtd.forms.native.fltk/src/xtd/forms/native/fltk/timer.cpp#L17

**Comment by gammasoft71** [comment]
Were further update candidates left over? :thinking:
* https://github.com/gammasoft71/xtd/blob/022e5450ba157378f4a26f04de1b4ecb03531200/src/xtd.core/include/xtd/web/css/css_writer.h#L25 --> No because it depends on the constructor used.
* https://github.com/gammasoft71/xtd/blob/26e93bb8e656974e347ea84abba4917b0eb8444e/src/xtd.core/src/xtd/net/sockets/send_packets_element.cpp#L32 --> No because it depends on the constructor used.
* https://github.com/gammasoft71/xtd/blob/032935f7d6e35d8dedf26490f96e50c3b31d5045/src/xtd.forms.native.fltk/src/xtd/forms/native/fltk/timer.cpp#L17 --> No because it an handle on the backend resource in this case, an FLTK resource.

**Comment by elfring** [comment]
>No because it depends on the constructor used.

:thought_balloon: Why are you concerned about such an implementation detail?

:eyes: [Is the null pointer check redundant for the variable “text_writer_”](https://github.com/gammasoft71/xtd/issues/214#issuecomment-1426811227 "Removing unnecessary null pointer checks")?


>No because it an handle on the backend resource in this case, an FLTK resource.

Can smart pointers take care of “handles” accordingly? :thinking:

**Comment by gammasoft71** [comment]
No because it depends on the constructor used.
💭 Why are you concerned about such an implementation detail?

👀 https://github.com/gammasoft71/xtd/issues/214#issuecomment-1426811227?

--> Indeed the nullptr test is redundant, I had not seen it 🤣

No because it an handle on the backend resource in this case, an FLTK resource.
Can smart pointers take care of “handles” accordingly? 🤔

--> In this case a smart pointer cannot be used.

There are two distinct libraries that use a third one for the definition of interfaces.
* xtd.form : This library has the responsibility to manage UI components without knowing the specific implementation of the platform on which the framework is executed.
* xtd.form.native.xxx : This library has the responsibility to create, modify and delete native resources specific to a given platform. This platform can be : Win32, Gtk, Cocoa, wxWidgets, SDL, ...
* xtd.form.native : This library is only an interface that allows to create the dialog between the xtd.forms library and the xtd.forms.native.xxx library.
See [xtd.forms.overview](https://gammasoft71.github.io/xtd/docs/documentation/Guides/xtd.forms/Overview/xtd_forms_overview) for more information.

The xtd.forms.native.xxx library must not retain the native resource handle it creates for xtd.form.
A handle has no type by definition since we want to isolate the xtd.corms library from the native implementation xtd.forms.native.xxx. 
Moreover, depending on the implementation of the xtd.forms.native.xxx library, there is not necessarily a pointer created by a new, it could even be that the memory is already managed by the native layer.

The handle is provided to the xtd.forms library and it is this one which has the responsibility of the handle management.
So we can't use smart pointers in the xtd.forms.native.xxx library.

I'll modify the code so that your tool doesn't see it as an error 😉

**Comment by elfring** [comment]
:crystal_ball: Will the application of custom deleters grow (for some “handles”)?

**Comment by gammasoft71** [comment]
❔ Sorry, but I don't understand your question. What do you mean by "the application of custom suppressors is growing"? Do you want to know if there is a risk of memory leakage?

If this is what you are talking about, there is no risk because creation and destruction are handled in one place by the base object xtd::forms::control. If we add a parent to the control, a native resource is created. If we delete the parent, the native resource is destroyed. And if we change the parent, the current native resource is destroyed and a new native resource is created. See [xtd.forms.overview](https://gammasoft71.github.io/xtd/docs/documentation/Guides/xtd.forms/Overview/xtd_forms_overview) and [documentation](https://gammasoft71.github.io/xtd/docs/documentation) for more information. 😉

**Comment by elfring** [comment]
:thought_balloon: I would like to point the software design possibility out to use also also custom deleters for special data types (and not “suppressors”).
Are you familiar with corresponding options?

**Comment by gammasoft71** [comment]
If you are talking about operator overload, yes, otherwise no.

**Comment by elfring** [comment]
:thought_balloon: [Custom deleters can be configured as a template parameter for smart pointers](https://en.cppreference.com/w/cpp/memory/unique_ptr/get_deleter "Documentation"), can't they?

**Comment by gammasoft71** [comment]
Again this makes no sense in this case.

See the xtd.form.native and xtd.forms.native.xxx libraries rather as a wrapper on a low level api like `CreateWindow` and `DestroyWindow` of the Win32 API...

xtd.forms.native contains the definition of both api:

```cpp
/// @brief Native API of window
class native_window {
protected:
  /// @brief Create a window...
  intptr_t create();

  /// @brief Detroy a window from handle...
  void destroy(intptr_t handle);
};
```

xtd.form.native.win32 contains the implementation for Win32 :

```cpp
intptr_t native_window::create() {
  return reinterpret_cast<intptr_t>(CreateWindow(/* some params */));
}

void native_window::destroy(intptr_t handle) {
  DestroyWindow(reinterpret_cast<HANDLE>(handle));
}
```

xtd.form.native.wxwidgets contains the implementation for wxWidgets :


```cpp
intptr_t native_window::create() {
  return reinterpret_cast<intptr_t>(new wxFrame(/* some params */));
}

void native_window::destroy(intptr_t handle) {
  reinterpret_cast<wxFrame*>(handle))->Destroy();
}
```

xtd.form.native.fltk contains the implementation for FLTK :

```cpp
intptr_t native_window::create() {
  return reinterpret_cast<intptr_t>(new Fl_Window(/* some params */));
}

void native_window::destroy(intptr_t handle) {
  delete reinterpret_cast<Fl_Window*>(handle));
}
```

Creation, type and destruction have nothing to do with a pointer and even less with a smart pointer.
A smart pointer will never work with the Win32 API, it will dump with wxWidgets which can only until Destroy because it has its own memory management.
Even if your proposals are, and I agree with you 100%, what we have to do with modern C++ code, they can't be applied with pure C libraries or APIs or pre-C++11 C++.

I hope this is clearer for you 😉
