### ISSUE TITLE
[BUG] reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [gammasoft71/xtd#218]
I would like to point out that identifiers like “[`__xtd_gtk_enable_dark_mode__`](https://github.com/gammasoft71/xtd/blob/cdcc739c26055f91e900989a954db5a10d206d44/src/xtd.forms.native.wxwidgets/src/xtd/forms/native/wxwidgets/application.cpp#L45 "Update candidate")” and “[`__tunit_main`](https://github.com/gammasoft71/xtd/blob/022e5450ba157378f4a26f04de1b4ecb03531200/src/xtd.tunit/include/xtd/tunit/tunit_main.h#L9 "Another update candidate")” [do eventually not fit](https://wiki.sei.cmu.edu/confluence/display/cplusplus/DCL51-CPP.+Do+not+declare+or+define+a+reserved+identifier "Do not declare an identifier which is reserved for the compiler implementation.") to the expected naming convention of the C++ language standard.
Would you like to adjust your selection for unique names?

**Comment by gammasoft71** [comment]
I know this rule.
But I deliberately name the hidden, non-public internal variables with a double _.
As they are not public variables, if really by bad luck the implementation of c++ or std would use one of my internal variables, I would just have to rename it. 
Because obviously the simplest compiler would give me the error. 
Moreover, having to use a tripple _ is really awful to use.
So this is not a bug for me. It will stay like this 😉.

**Comment by elfring** [comment]
:thought_balloon: How do you think about to avoid that this software [depends on undefined behaviour](https://www.securecoding.cert.org/confluence/display/c/CC.+Undefined+Behavior#CC.UndefinedBehavior-ub_106 "Avoiding undefined behaviour?")?
