### ISSUE TITLE
[BUG] Unable to compiling on Linux/GCC with Meson and CMake module

### ISSUE THREAD

**Issue by Yrds** [gammasoft71/xtd#230]
# Describe the bug

I'm trying to using meson with cmake module. The library compiles, but when compiling main.cpp and got errors.

# To Reproduce

- Compile this project: https://github.com/Yrds/xtd-linux-test
- See error ([build.log](https://github.com/gammasoft71/xtd/files/12176450/build.log))

# Expected behaviour

Compile without errors

# Desktop

 - OS: Archlinux
 - Version: 
 - xtd version:  0.1.1-beta
 - GCC: 13.1.1 20230714

**Additional context**

One of the errors is `‘days’ is not a member of ‘std::chrono’` and I've seen std::chrono::days is defined some under circunstances. I guess it have something like to [this](https://github.com/gammasoft71/xtd/blob/d544a454d1bf5dfff1fe06b5e42b1fe35d173de0/src/xtd.core/include/xtd/internal/__duration_formatter.h#L16).

PS: I know you guys don't support meson but I'm not doing nothing fancy, just importing cmake project into my dependencies and trying to compiling.

**Workaround**

No workaround

**Comment by gammasoft71** [comment]
Hello,

**First of all, thank you for your interest in xtd.**

**Thank you for your feedback.**

I don't use Archlinux but Ubuntu, but I do use g++-13 like you. And xtd builds and runs correctly.
I don't know Meson (well, I know its name and what it's used for lol), I've never used it, so I don't know how it interfaces with CMake.

What I can tell you depends on the errors I see: The problem may lie with the c++ version.
At the very least, you need to use version c++17, otherwise there will be compilation errors.
Maybe there's a problem with the definition of the c++ standard between CMake and Meson. Because xtd's c++ standard definition with CMake is done through my own macro: `choice_options`.

* Here's its definition:
```CMake
## @brief Provides a choice options for the user to select an option from options list.
## @param OPTION the option to set.
## @param MESSAGE Description message for the choice options.
## @param DEFAULT_OPTION The default option.
## @param ... Other options.
## @remarks This method must be called before target_type().
## @remarks This method is optional. 
## @par Examples
## @code
## cmake_minimum_required(VERSION 3.3)
##
## project(my_project)
## find_package(xtd REQUIRED)
## add_sources(my_project.cpp)
##  
## choice_options(TARGET_TYPE "Choose library dynamic, static, interface or module" DINAMIC_LIBRARY STATIC_LIBRARY INTERFACE_LIBRARY MODULE_LIBRARY)
## target_type(${TARGET_TYPE})
## @endcode
macro(choice_options OPTION MESSAGE DEFAULT_OPTION)
  set(${OPTION} ${DEFAULT_OPTION} CACHE STRING ${MESSAGE})
  set_property(CACHE ${OPTION} PROPERTY STRINGS ${DEFAULT_OPTION} ${ARGN})
endmacro ()
```

* Here's how it's used to define the c++ standard:
```CMake
# standard C++
choice_options(XTD_BUILD_CPP_STANDARD "Choose c++ stadard to build xtd projects" 20 17 14 11 98 compiler_default)
if (NOT "${XTD_BUILD_CPP_STANDARD}" STREQUAL "compiler_default")
  set(CMAKE_CXX_STANDARD ${XTD_BUILD_CPP_STANDARD})
  set(CMAKE_CXX_STANDARD_REQUIRED ON)
endif ()
```

* Make sure that the `CMAKE_CXX_STANDARD` variable is set to `20` or `17` and that the `CMAKE_CXX_STANDARD_REQUIRED` variable is set to `ON`.
You can add traces in CMake with the `message()` command.

## For information: 

Type `xtd::chrono::days` is only defined in c++20 but xtd, is normally able to define it for c++17. 
This type is only used for date formatting and for the system_report object.

I need to add the xtd::time_span class by then. Then I won't need std::chrono::days.
For the moment, xtd::time_span is only a typedef on xtd::ticks, which is itself only a typedef on std::chrono::duration<...>.

I hope this helps you solve your problem. Keep me informed of your investigations

Gammasoft

**Comment by Yrds** [comment]
You were right. I just set `CMAKE_CXX_STANDARD` to 20 and `CMAKE_CXX_STANDARD_REQUIRED` to `ON` and was able to compiling without compilation errors. 

Now I just have some system-wide dependencies to solve and I guess I can make xtd projects on meson.

Many Thanks!
