### ISSUE TITLE
[QUESTION] troubles when installing/compiling xtd

### ISSUE THREAD

**Issue by FoofooTheGuy** [gammasoft71/xtd#237]
I was trying to install xtd commit 03c8bcf on manjaro gnome 23.0-230903-linux65 and when it gets to this linking step, it has an error.
I don't think this is a problem with xtd itself so I set this issue as a question.

Here is a copy of the terminal output:
```[ 98%] Built target xtd
[ 98%] Building CXX object tools/guidgen-gui/CMakeFiles/guidgen-gui.dir/properties/startup.cpp.o
[ 98%] Building CXX object tools/xtdc-gui/CMakeFiles/xtdc-gui.dir/src/project_type_item_control.cpp.o
[ 98%] Building CXX object tools/xtdc-gui/CMakeFiles/xtdc-gui.dir/properties/startup.cpp.o
[ 98%] Building CXX object tools/xtdc-gui/CMakeFiles/xtdc-gui.dir/src/main_form.cpp.o
[ 98%] Linking CXX executable guidgen-gui
/usr/bin/ld: /usr/local/lib/libwx_gtk3u_core-3.1.a(display.cpp.o): undefined reference to symbol 'XListDepths'
/usr/bin/ld: /usr/lib/libX11.so.6: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
make[2]: *** [tools/guidgen-gui/CMakeFiles/guidgen-gui.dir/build.make:112: tools/guidgen-gui/guidgen-gui] Error 1
make[1]: *** [CMakeFiles/Makefile2:948: tools/guidgen-gui/CMakeFiles/guidgen-gui.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 98%] Linking CXX executable xtdc-gui
/usr/bin/ld: /usr/local/lib/libwx_gtk3u_core-3.1.a(display.cpp.o): undefined reference to symbol 'XListDepths'
/usr/bin/ld: /usr/lib/libX11.so.6: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
make[2]: *** [tools/xtdc-gui/CMakeFiles/xtdc-gui.dir/build.make:144: tools/xtdc-gui/xtdc-gui] Error 1
make[1]: *** [CMakeFiles/Makefile2:1040: tools/xtdc-gui/CMakeFiles/xtdc-gui.dir/all] Error 2
make: *** [Makefile:146: all] Error 2
```
What should I install or do to fix this error?

**Comment by gammasoft71** [comment]
Hi there,

Thank you for your report ;-)

I've never had this kind of problem.
From the traces it looks like a method/library referencing problem...

* Could you check the integrity of your packages with your package manager (`pacman` I presume).
* Updgrade/update packages? 
* Delete the `build` folder in xtd.
* Relaunch xtd `install`.

I haven't retested the install of xtd version 0.1.1 on manjaro. The previous version worked. 
And given the low level of changes between 0.1.0 and 0.1.1, I doubt that's where the problem lies.

Keep me up to date. If you can't, I'll do another test on my side.

Sincerely
Gammasoft.

**Comment by FoofooTheGuy** [comment]
Deleting the `build` folder made it work, I should have tried that first... Thanks for your advice!
