### ISSUE TITLE
Why does the hello world example not running ?

### ISSUE THREAD

**Issue by Mamograg17** [gammasoft71/xtd#41]
i tried to build hello world app from the examples in the examples folder,
```
#include <xtd/xtd>

using namespace xtd::forms;

class main_form : public form {
public:
  main_form() {
    text("Hello world (message_box)");
    button1.location({10, 10});
    button1.parent(*this);
    button1.text("&Click me");
    button1.click += [] {
      message_box::show("Hello, World!");
    };
  }
  
private:
  button button1;
};

int main() {
  application::run(main_form());
}

```
this code is from github, but when i run `xtdc run` i get :
```
[ 33%] Linking CXX executable gui_app1
/usr/bin/ld: CMakeFiles/gui_app1.dir/properties/startup.cpp.o: in function `main':
startup.cpp:(.text+0x20): multiple definition of `main'; CMakeFiles/gui_app1.dir/src/form1.cpp.o:form1.cpp:(.text+0x0): first defined here
/usr/bin/ld: CMakeFiles/gui_app1.dir/properties/startup.cpp.o: in function `main':
startup.cpp:(.text+0x3c): undefined reference to `gui_app1::form1::main()'
collect2: error: ld returned 1 exit status
make[2]: *** [gui_app1/CMakeFiles/gui_app1.dir/build.make:125: gui_app1/gui_app1] Error 1
make[1]: *** [CMakeFiles/Makefile2:152: gui_app1/CMakeFiles/gui_app1.dir/all] Error 2
make: *** [Makefile:146: all] Error 2
Build error! Run project aborted.

```

is this a problem with the code or the framework.

**Comment by gammasoft71** [comment]
# You problem

You probably created a project from xtdc-gui or xtdc.
Then you copy/paste the code from the xtd homepage on github.

When you created the project with xtdc-gui, you created a project whose file **gui_app1/gui_app1/properties/target_properties.cmake** which contains this:

```shell
target_default_namespace("gui_app1")
target_icon(resources/gui_app1)
target_name("gui_app1")
target_startup("gui_app1::form1" src/form1.h)
```

The last command **[target_startup](https://codedocs.xyz/gammasoft71/xtd/_c_make_commands.html#TargetStartupSubSection)("gui_app1::form1" src/form1.h)** The last command specifies that CMake will automatically generate the file **gui_app1/gui_app1/properties/starup.cpp** which will contain : 

```c++
#pragma region xtd generated code
// This code was generated by CMake script.
//
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.

#include "../src/form1.h"
#include <xtd/startup.h>

startup_(gui_app1::form1);
#pragma endregion
```

In this file, the second to last line **startup_(gui_app1::form1);** expects the main function to be in the class *gui_app1::form1*.

This is no longer the case after your copy/paste.

Two solutions are available to you.

# Solution 1

Move the main function into the *gui_app1:::form1* class like this:

```c++
namespace gui_app1 {
  #include <xtd/xtd>
  
  using namespace xtd::forms;
  
  class form1 : public form {
  public:
    main_form() {
      text("Hello world (message_box)");
  
      button1.location({10, 10});
      button1.parent(*this);
      button1.text("&Click me");
      button1.click += [] {
        message_box::show("Hello, World!");
      };
    }
    
    static void main() {
      application::run(form1());  
    }
    
  private:
    button button1;
  };
}
```

# Solution 2

Delete the file **gui_app1/gui_app1/properties/target_properties.cmake**. This way the **startup.cpp** file will not be generated anymore.
Re-generate the solution with *CMake* command so that it takes your changes into account.

And use the following code:

```c++
#include <xtd/xtd>

using namespace xtd::forms;

class main_form : public form {
public:
  main_form() {
    text("Hello world (message_box)");

    button1.location({10, 10});
    button1.parent(*this);
    button1.text("&Click me");
    button1.click += [] {
      message_box::show("Hello, World!");
    };
  }
  
private:
  button button1;
};

int main() {
  application::run(main_form());
}
```

# Remarks

The advantage of solution 1 is that the main behind the [startup_](https://codedocs.xyz/gammasoft71/xtd/group__keywords.html#gac9b8e6f22fb2fdc1bb915ee01aef848c) function already contains the try and catch for the whole application with a generic message in case of exception.
If you use solution 2, you will have to write the try and catch yourself like this:

```C++
int main() {
  try {
    application::run(main_form());
  } catch(const xtd::system_exception& e) {
    xtd::forms::exception_box::show(e, xtd::forms::application::product_name());  
  } catch(const std::exception& e) {
    xtd::forms::exception_box::show(e, xtd::forms::application::product_name());  
  } catch(...) {
    xtd::forms::exception_box::show(xtd::forms::application::product_name());  
  }

}
```

# Documentations

I advise you to read the following documentations to have a good understanding of xtd:

 - [guides](https://github.com/gammasoft71/xtd/blob/master/docs/guides.md)
 - [CMake](https://codedocs.xyz/gammasoft71/xtd/_c_make_commands.html#TargetStartupSubSection)
 - [startup_](https://codedocs.xyz/gammasoft71/xtd/group__keywords.html#gac9b8e6f22fb2fdc1bb915ee01aef848c)
 - [Reference Guide](https://codedocs.xyz/gammasoft71/xtd/index.html)

**Comment by Mamograg17** [comment]
Thank you, i also want to know what does `button1.parent(*this);` means because it's not included in the documentation.

**Comment by gammasoft71** [comment]
An [xtd::forms::button](https://codedocs.xyz/gammasoft71/xtd/classxtd_1_1forms_1_1button.html) inherits from [xtd::forms::control](https://codedocs.xyz/gammasoft71/xtd/classxtd_1_1forms_1_1control.html) (like all [controls](https://codedocs.xyz/gammasoft71/xtd/group__controls.html) and all [containers](https://codedocs.xyz/gammasoft71/xtd/group__containers.html))
And the [xtd::forms::control::parent](https://codedocs.xyz/gammasoft71/xtd/classxtd_1_1forms_1_1control.html#ae4a242f021c5a1e5da94862ccdd10b67) property is part of the properties of a [xtd::forms::control](https://codedocs.xyz/gammasoft71/xtd/classxtd_1_1forms_1_1control.html).

This property is documented [here](https://codedocs.xyz/gammasoft71/xtd/classxtd_1_1forms_1_1control.html#ae4a242f021c5a1e5da94862ccdd10b67).

And this means simply in this case that the button belongs to **this** pointer in this case **form1**.
